### ISSUE TITLE
Functionbeat not working with Al2 runtime

### ISSUE THREAD

**Issue by pauliuspetka** [PacoVK/terraform-aws-functionbeat#9]
Hi!

I noticed you have figured out how to deploy functionbeat on al2 runtime. I was trying in pretty same way as you, but im getting timeout on init:
<img width="1194" alt="image" src="https://github.com/PacoVK/terraform-aws-functionbeat/assets/51696725/375542ac-277f-4555-9c83-821a0b8a3ca5">

Any ideas what could cause this issue? i have enabled debug mode, but absolutely no difference...

downloading same way executable:
```
SYSTEM="$(uname | awk '{print tolower($0)}')"
FUNCTION_BEAT_URL=https://artifacts.elastic.co/downloads/beats/functionbeat/functionbeat-"${FB_FUNCTIONBEAT_VERSION}"-"${SYSTEM}"-x86_64.tar.gz

DESTINATION=functionbeat-"${FB_FUNCTIONBEAT_VERSION}"-"${SYSTEM}"-x86_64

export BEAT_STRICT_PERMS=false
# export ENABLED_FUNCTION="${ENABLED_FUNCTION}"

if [ ! -d "${DESTINATION}" ]; then
  curl -s "${FUNCTION_BEAT_URL}" > "${DESTINATION}".tar.gz
  tar xzvf "${DESTINATION}".tar.gz > /dev/null
  tar -xf $BUILD_DIST_DIR/$DESTINATION.tar.gz -C $BUILD_DIST_DIR
  rm -rf $BUILD_DIST_DIR/$DESTINATION.tar.gz
fi
```

Making package:
`(cd $DESTINATION && ./functionbeat -v --strict.perms=false -e package --output ../$BUILD_ZIP_FILE > /dev/null)`

Chaging executable name to bootstrap:
```
mv $BUILD_DIST_DIR/functionbeat/functionbeat-aws $BUILD_DIST_DIR/functionbeat/bootstrap
chmod go-w $BUILD_DIST_DIR/functionbeat/functionbeat.yml
```
 terraform:

```
resource "aws_lambda_function" "functionbeat_lambda" {
  count         = local.disable_log_forwarding
  function_name = local.functionbeat_lambda_name
  role          = aws_iam_role.functionbeat_role[0].arn

  filename         = "${path.module}/scripts/functionbeat/functionbeat.zip"
  source_code_hash = try(filebase64sha256("${path.module}/scripts/functionbeat/functionbeat.zip"), null)

  handler = "null.handler"
  runtime = "provided.al2"
  architectures = ["x86_64"]

  description                    = "Sends lambda logs from cloudwatch to ELK"
  memory_size                    = 1024
  timeout                        = 900
  reserved_concurrent_executions = -1
  publish                        = upper(local.environment_prefix) == "PROD" ? true : false
  layers                         = []

  environment {
    variables = merge({
      BEAT_STRICT_PERMS = "false"
      ENABLED_FUNCTIONS = "cloudwatch"
    }, local.functionbeat_build_variables)
  }

  tags = merge(local.shared_tags, {
    Name = format("%.64s", upper("${local.name_prefix}-functionbeat"))
  })

  depends_on = [aws_cloudwatch_log_group.lambda_log_group, data.external.build_functionbeat, aws_cloudwatch_log_group.functionbeat_lambda_log_group]
}
```

functionbeat.yml after build:
```
fields:
  AWSAccountID: account_id
  AWSAccountName: account_name
  environment: dev
  source_app: lambda
fields_under_root: true
functionbeat:
  provider:
    aws:
      deploy_bucket: bucket_name
      endpoint: s3.amazonaws.com
      functions:
      - description: lambda function for cloudwatch logs
        enabled: true
        name: cloudwatch
        triggers:
        - log_group_name: /aws/lambda/functionbeat-cloudwatch_logs
        type: cloudwatch_logs
keystore:
  path: /tmp/functionbeat.keystore
logging:
  level: debug
  metrics:
    enabled: false
  selectors:
  - '*'
metricbeat:
  metrics:
  - enabled: false
name: functionbeat
output:
  logstash:
    hosts:
    - host:5044
    pipelining: 0
    ssl:
      certificate: beat.crt
      certificate_authorities:
      - elasticsearch-ca.crt
      enabled: true
      key: beat.key
processors:
- decode_json_fields:
    add_error_key: true
    fields:
    - message
    max_depth: 1
    overwrite_keys: true
    process_array: true
    target: ""
- add_tags:
    tags:
    - functionbeat_by_lambda_module
queue:
  mem:
    flush:
      min_events: 10
      timeout: 0.01s
setup:
  template:
    enabled: true

```

any ideas what im missing? thanks in advance if you have any hints!
